app: vjepa_droid
cpus_per_task: 4
folder: outputs/train/libero-vjepa21-vitb-ac-pilot
mem_per_gpu: 64G
nodes: 1
tasks_per_node: 1
data:
  dataset_format: libero
  batch_size: 1
  crop_size: 256
  datasets:
  - data/libero/libero_spatial_h5_paths.csv
  dataset_fpcs:
  - 8
  fps: 4
  libero_camera_key: agentview_rgb
  libero_frame_stride: 1
  num_workers: 0
  patch_size: 16
  persistent_workers: false
  pin_mem: false
  stereo_view: false
  tubelet_size: 2
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1.0
  - 1.0
  random_resize_scale:
  - 1.0
  - 1.0
  reprob: 0.0
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_predictor: false
  pretrain_checkpoint: checkpoints/vjepa2_1_vitb_dist_vitG_384.pt
  context_encoder_key: ema_encoder
  target_encoder_key: ema_encoder
  resume_checkpoint: null
  save_every_freq: -1
  seed: 239
  use_sdpa: true
model:
  compile_model: false
  model_name: vit_base
  pred_depth: 12
  pred_embed_dim: 384
  pred_is_frame_causal: true
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_pred_silu: false
  use_rope: true
  use_silu: false
  wide_silu: true
optimization:
  anneal: 5
  betas:
  - 0.9
  - 0.999
  enc_lr_scale: 0.1
  epochs: 5
  eps: 1.0e-8
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: null
  lr: 0.0001
  start_lr: 0.00001
  warmup: 1
  weight_decay: 0.04
